Repository woowacourse/java-jdbc, pull requests merged in 2025-10, with the labels that each got.

#954 [1단계 - JDBC 라이브러리 구현하기] 피글렛(김은수) 미션 제출합니다.
  app/build.gradle
  app/src/main/java/com/techcourse/dao/UserDao.java
  app/src/main/java/com/techcourse/dao/UserHistoryDao.java
  app/src/test/java/com/techcourse/dao/UserDaoTest.java
  jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
  jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
Labels: step1

#966 [1단계 - JDBC 라이브러리 구현하기] - 코기(장재현) 미션 제출합니다
  app/build.gradle
  app/src/main/java/com/techcourse/dao/UserDao.java
  jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
  jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
  study/src/test/java/connectionpool/PoolingVsNoPoolingTest.java
Labels: step1

#963 [2단계 - 리팩터링] 투다(박찬양) 미션 제출합니다.
  app/src/main/java/com/techcourse/dao/UserDao.java
  app/src/main/resources/schema.sql
  jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
  jdbc/src/main/java/com/interface21/jdbc/exception/JdbcFailException.java
Labels: step2

#962 [1단계 - JDBC 라이브러리 구현하기] 웨이드(고선제) 미션 제출합니다.
  app/src/main/java/com/techcourse/dao/UserDao.java
  app/src/main/java/com/techcourse/support/jdbc/init/DatabasePopulatorUtils.java
  jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
  jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
  study/src/test/java/transaction/stage1/Stage1Test.java
  study/test.mv.db
Labels: step1

#978 [1단계 - JDBC 라이브러리 구현하기] 레몬(윤웅찬) 미션 제출합니다.
  app/src/main/java/com/techcourse/ManualHandlerMapping.java
  app/src/main/java/com/techcourse/controller/LoginController.java
  app/src/main/java/com/techcourse/controller/RegisterController.java
  app/src/main/java/com/techcourse/dao/UserDao.java
  app/src/main/java/com/techcourse/dao/UserHistoryDao.java
  app/src/main/java/com/techcourse/service/UserService.java
  app/src/test/java/com/techcourse/dao/UserDaoTest.java
  app/src/test/java/com/techcourse/service/UserServiceTest.java
  jdbc/src/main/java/com/interface21/dao/EmptyResultDataAccessException.java
  jdbc/src/main/java/com/interface21/dao/OverSizeResultDataAccessException.java
  jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
  jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementValue.java
  jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
  study/src/test/java/connectionpool/PoolingVsNoPoolingTest.java
  study/src/test/java/transaction/stage1/Stage1Test.java
  study/src/test/java/transaction/stage2/FirstUserService.java
  study/src/test/java/transaction/stage2/Stage2Test.java
  study/test.mv.db
  study/test.trace.db
Labels: step1

#982 [1단계 - JDBC 라이브러리 구현하기] - 포스티(윤강민) 미션 제출합니다.
  app/build.gradle
  app/src/main/java/com/techcourse/dao/UserDao.java
  app/src/main/resources/schema.sql
  app/src/test/java/com/techcourse/dao/UserDaoTest.java
  jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
  jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
  study/src/test/java/connectionpool/PoolingVsNoPoolingTest.java
  study/src/test/java/connectionpool/stage0/Stage0Test.java
Labels: step1

#936 [1단계 - JDBC 라이브러리 구현하기] 히로(진승희) 미션 제출합니다.
  app/build.gradle
  app/src/main/java/com/techcourse/dao/UserDao.java
  app/src/test/java/com/techcourse/dao/UserDaoTest.java
  jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
  jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementCallback.java
  jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
Labels: step1

#980 [1단계 - JDBC 라이브러리 구현하기] 부기(이창의) 미션 제출합니다.
  app/build.gradle
  app/src/main/java/com/techcourse/dao/UserDao.java
  app/src/main/java/com/techcourse/domain/User.java
  app/src/test/java/com/techcourse/dao/UserDaoTest.java
  jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
  jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
  study/src/test/java/connectionpool/PoolingVsNoPoolingTest.java
Labels: step1

#950 [1단계 - JDBC 라이브러리 구현하기] - 플린트(이주환) 미션 제출합니다
  app/build.gradle
  app/src/main/java/com/techcourse/controller/LoginController.java
  app/src/main/java/com/techcourse/controller/RegisterController.java
  app/src/main/java/com/techcourse/dao/UserDao.java
  app/src/main/java/com/techcourse/service/UserService.java
  jdbc/src/main/java/com/interface21/jdbc/core/JdbcCallback.java
  jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
  jdbc/src/main/java/com/interface21/jdbc/core/ParameterBinder.java
  jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
  jdbc/src/main/java/com/interface21/jdbc/core/TypeBinder.java
Labels: step1

#970 [1단계 - JDBC 라이브러리 구현하기] - 루키(김준하) 미션 제출합니다.
  app/build.gradle
  app/src/main/java/com/techcourse/dao/UserDao.java
  app/src/main/resources/schema.sql
  app/src/test/java/com/techcourse/dao/UserDaoTest.java
  jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
  jdbc/src/main/java/com/interface21/jdbc/core/ResultMapper.java
Labels: step1

#974 [2단계 - 리팩터링] 훌라(김성준) 미션 제출합니다.
  jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
  jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementSetter.java
Labels: step2

#997 [1단계 - JDBC 라이브러리 구현하기] 히포(권건형) 미션 제출합니다.
  app/build.gradle
  app/src/main/java/com/techcourse/dao/UserDao.java
  jdbc/build.gradle
  jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
  jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
  mvc/build.gradle
  study/src/test/java/connectionpool/PoolingVsNoPoolingTest.java
  study/src/test/java/connectionpool/stage0/Stage0Test.java
  study/src/test/java/connectionpool/stage2/Stage2Test.java
Labels: step1

#956 [1단계 - JDBC 라이브러리 구현하기] 메이(김시원) 미션 제출합니다.
  app/build.gradle
  app/src/main/java/com/techcourse/dao/UserDao.java
  app/src/main/java/com/techcourse/dao/UserRowMapper.java
  app/src/test/java/com/techcourse/dao/UserDaoTest.java
  jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
  jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
  study/src/test/java/connectionpool/PoolingVsNoPoolingTest.java
Labels: step1

#994 [2단계 - 리팩터링] 머피(송제용) 미션 제출합니다.
  app/src/main/java/com/techcourse/dao/UserDao.java
  jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
  jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementFactory.java
  jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementSetter.java
  jdbc/src/main/java/com/interface21/jdbc/core/SqlExecutor.java
Labels: step2

#967 [1단계 - JDBC 라이브러리 구현하기] - 노랑 미션 제출합니다
  app/build.gradle
  app/src/main/java/com/techcourse/dao/UserDao.java
  jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
  jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
Labels: step1

#993 [1단계 - JDBC 라이브러리 구현하기] 리버(이연후) 미션 제출합니다.
  app/build.gradle
  app/src/main/java/com/techcourse/dao/UserDao.java
  app/src/test/java/com/techcourse/dao/UserDaoTest.java
  jdbc/build.gradle
  jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
  jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
  study/src/test/java/connectionpool/stage0/Stage0Test.java
  study/src/test/java/transaction/stage1/Stage1Test.java
  study/src/test/java/transaction/stage2/FirstUserService.java
  study/src/test/java/transaction/stage2/Stage2Test.java
Labels: step1

#973 [1단계 - JDBC 라이브러리 구현하기] - 호떡(민경윤) 미션 제출합니다.
  app/src/main/java/com/techcourse/dao/UserDao.java
  app/src/test/java/com/techcourse/service/UserServiceTest.java
  jdbc/src/main/java/com/interface21/jdbc/JdbcTemplate.java
  jdbc/src/main/java/com/interface21/jdbc/RowMapper.java
  study/src/test/java/connectionpool/PoolingVsNoPoolingTest.java
Labels: step1

#1004 Step1 띠용
  app/build.gradle
  app/src/main/java/com/techcourse/dao/UserDao.java
  app/src/main/java/com/techcourse/dao/UserRowMapper.java
  app/src/test/java/com/techcourse/DbCleaner.java
  app/src/test/java/com/techcourse/dao/UserDaoTest.java
  jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
  jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
  study/src/test/java/connectionpool/stage0/Stage0Test.java
Labels: step1

#998 [1단계 - JDBC 라이브러리 구현하기] 듀이(이주희) 미션 제출합니다.
  app/build.gradle
  app/src/main/java/com/techcourse/dao/UserDao.java
  app/src/main/java/com/techcourse/dao/UserHistoryDao.java
  app/src/main/java/com/techcourse/service/UserService.java
  app/src/test/java/com/techcourse/dao/UserDaoTest.java
  app/src/test/java/com/techcourse/service/UserServiceTest.java
  jdbc/build.gradle
  jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
  jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementSetter.java
  jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
  jdbc/src/test/java/com/interface21/jdbc/core/JdbcTemplateTest.java
  study/src/test/java/connectionpool/PoolingVsNoPoolingTest.java
Labels: step1

#1012 [1단계 - JDBC 라이브러리 구현하기] 벡터(백승주) 미션 제출합니다.
  app/build.gradle
  app/src/main/java/com/techcourse/dao/UserDao.java
  jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
  jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
  study/src/test/java/connectionpool/PoolingVsNoPoolingTest.java
Labels: step1

#1002 [1단계 - JDBC 라이브러리 구현하기] 비타(오연택) 미션 제출합니다.
  app/build.gradle
  app/src/main/java/com/techcourse/dao/UserDao.java
  app/src/test/java/com/techcourse/dao/UserDaoTest.java
  jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
Labels: step1

#1005 [2단계 - 리팩터링] 폰트(김영재) 미션 제출합니다.
  app/src/main/java/com/techcourse/dao/UserDao.java
  jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
  jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementCallback.java
  jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementSetter.java
Labels: step2

#989 [2단계 - 리팩터링] 줄리(한승아) 미션 제출합니다.
  app/src/main/java/com/techcourse/controller/LoginController.java
  app/src/main/java/com/techcourse/controller/RegisterController.java
  app/src/main/java/com/techcourse/service/UserService.java
  jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
  jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementParamMapping.java
  jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementSetter.java
  jdbc/src/main/java/com/interface21/jdbc/core/QueryExecutor.java
Labels: step2

#1020 [2단계 - 리팩터링] 강산(조재중) 미션 제출합니다.
  app/src/main/resources/schema.sql
  jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
Labels: step2

#1016 [3단계 - Transaction 적용하기] 돔푸(이창근) 미션 제출합니다.
  app/src/main/java/com/techcourse/service/UserService.java
  app/src/test/java/com/techcourse/service/UserServiceTest.java
  jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
  jdbc/src/main/java/com/interface21/jdbc/core/Transaction.java
  jdbc/src/main/java/com/interface21/jdbc/core/TransactionHolder.java
  jdbc/src/main/java/com/interface21/jdbc/dsl/component/DbObject.java
Labels: step3

#957 [1단계 - JDBC 라이브러리 구현하기] 칼리(이진) 미션 제출합니다.
  app/build.gradle
  app/src/main/java/com/techcourse/dao/UserDao.java
  app/src/test/java/com/techcourse/dao/UserDaoTest.java
  jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
  jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
  study/src/test/java/connectionpool/PoolingVsNoPoolingTest.java
  study/src/test/java/transaction/stage1/Stage1Test.java
Labels: step1

#1018 [1단계 - JDBC 라이브러리 구현하기] 짱구(박준혁) 미션 제출합니다.
  app/build.gradle
  app/src/main/java/com/techcourse/dao/UserDao.java
  app/src/main/java/com/techcourse/dao/UserHistoryDao.java
  app/src/test/java/com/techcourse/dao/UserDaoTest.java
  jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
  jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
Labels: step1

#1031 [2단계 - 리팩터링] 미소(이소은) 미션 제출합니다.
  jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
  jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementCallback.java
  jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementSetter.java
Labels: step2

#1009 [1단계 - JDBC 라이브러리 구현하기] 사나(조은산) 미션 제출합니다.
  app/build.gradle
  app/src/main/java/com/techcourse/dao/UserDao.java
  app/src/main/java/com/techcourse/dao/UserHistoryDao.java
  jdbc/README.md
  jdbc/build.gradle
  jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
  study/src/test/java/connectionpool/PoolingVsNoPoolingTest.java
  study/src/test/java/transaction/stage1/Stage1Test.java
  study/src/test/java/transaction/stage2/FirstUserService.java
  study/src/test/java/transaction/stage2/Stage2Test.java
Labels: step1

#1000 [1단계 - JDBC 라이브러리 구현하기] 서프(이재훈) 미션 제출합니다.
  app/build.gradle
  app/src/main/java/com/techcourse/dao/UserDao.java
  app/src/test/java/com/techcourse/dao/UserDaoTest.java
  jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
  jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementAction.java
  jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
  study/src/test/java/connectionpool/PoolingVsNoPoolingTest.java
  study/src/test/java/transaction/stage1/Stage1Test.java
Labels: step1

#1035 [3단계 - Transaction 적용하기] 훌라(김성준) 미션 제출합니다.
  app/src/main/java/com/techcourse/dao/UserDao.java
  app/src/main/java/com/techcourse/dao/UserHistoryDao.java
  app/src/main/java/com/techcourse/service/UserService.java
  app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
  app/src/test/java/com/techcourse/service/UserServiceTest.java
  jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
  jdbc/src/main/java/com/interface21/transaction/support/BusinessService.java
  jdbc/src/main/java/com/interface21/transaction/support/TransactionalMethod.java
Labels: step3

#1008 [1단계 - JDBC 라이브러리 구현하기] 슬링키(김민기) 미션 제출합니다.
  app/build.gradle
  app/src/main/java/com/techcourse/dao/UserDao.java
  app/src/main/java/com/techcourse/service/UserService.java
  app/src/test/java/com/techcourse/dao/UserDaoTest.java
  jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
  jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
  study/src/test/java/connectionpool/PoolingVsNoPoolingTest.java
Labels: step1

#1017 [2단계 - 리팩터링] 피글렛(김은수) 미션 제출합니다.
  jdbc/src/main/java/com/interface21/jdbc/IncorrectResultSizeException.java
  jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
  jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
Labels: step2

#987 [2단계 - 리팩터링] 헤일러(민서현) 미션 제출합니다.
  app/src/main/java/com/techcourse/dao/UserDao.java
  app/src/test/java/com/techcourse/dao/UserDaoTest.java
  jdbc/src/main/java/com/interface21/jdbc/core/ArgumentPreparedStatementSetter.java
  jdbc/src/main/java/com/interface21/jdbc/core/DataAccessException.java
  jdbc/src/main/java/com/interface21/jdbc/core/EmptyResultDataAccessException.java
  jdbc/src/main/java/com/interface21/jdbc/core/IncorrectResultSizeDataAccessException.java
  jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
  jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementSetter.java
  study/src/test/java/connectionpool/stage0/Stage0Test.java
  study/src/test/java/connectionpool/stage1/Stage1Test.java
  study/src/test/java/transaction/stage1/Stage1Test.java
  study/src/test/java/transaction/stage1/UserDao.java
  study/src/test/java/transaction/stage2/FirstUserService.java
  study/src/test/java/transaction/stage2/Stage2Test.java
Labels: step2

#1001 [2단계 - 리팩터링] 후유(김대동) 미션 제출합니다.
  app/src/main/java/com/techcourse/dao/UserDao.java
  app/src/test/java/com/techcourse/dao/UserDaoTest.java
  jdbc/src/main/java/com/interface21/jdbc/core/JdbcTemplate.java
  jdbc/src/main/java/com/interface21/jdbc/core/PositionalParameterPreparedStatementSetter.java
  jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementCallback.java
  jdbc/src/main/java/com/interface21/jdbc/core/PreparedStatementSetter.java
  jdbc/src/main/java/com/interface21/jdbc/core/RowMapper.java
Labels: step2
